name: Build

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Configure Git User Details
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
      
      # Spigot PLugin Build   
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew clean build
      - name: upload Spigot Plugin
        uses: actions/upload-artifact@v3
        with:
         name: CustomFishing
         path: target/*.jar
      - name: automatic releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
         repo_token: "${{ secrets.GITHUB_TOKEN }}"
         automatic_release_tag: "latest"
         prerelease: false
         title: "CustomFishing 自动构建最新版本"
         files: |
              target/*.jar
